Config:
  #prefix that you can use with %prefix%
  Prefix: '&b&lJoinEvents &3&l>>'
  Join:
    WelcomeMessage:
      #define if the welcome text is activated you can use "true/false"
      Enabled: true
      #defines the text of the welcome message
      Text:
        - '&3&m&l+---------------------------------------+'
        - '                      &bWelcome &b&l%player%'
        - ' '
        - '     &c&lYoutube: &cYour Youtube'
        - '        &3&lTwitter/x: &bYour twitter'
        - '           &b&l¡Visit our store mc.example.net!'
        - '&3&m&l+---------------------------------------+'
    TextForRank:
      #define if the welcome text for those who have permits is activated you can use "true/false"
      Enabled: true
      Permission:
        - 'je.vip'
        - 'je.vip+'
        - 'je.mvp'
        - 'je.mvp+'
      #defines the text when someone with permission enters
      EnteredMessages:
        - '&3&l[&b&l+&3&l] &3&lV&b&lip &b&l%player%'
        - '&3&l[&b&l+&3&l] &3&lV&b&lip3&l+ &b&l%player%'
        - '&6&l[&e&l+&6&l] &6&lMvp &6&l%player%'
        - '&6&l[&e&l+&6&l] &6&lMvp+ &6&l%player%'
      #defines the text when someone with permission exit
      LeavingMessages:
        - '&4&l[&c&l-&4&l] &3&lV&b&lip &b&l%player%'
        - '&4&l[&c&l-&4&l] &3&lV&b&lip3&l+ &b&l%player%'
        - '&4&l[&c&l-&4&l] &6&lMvp &6&l%player%'
        - '&4&l[&c&l-&4&l] &6&lMvp+ &6&l%player%'
      #defines the sound when someone with permission join
      SoundsJoin:
        -
        -
        -
        -
    Titles:
      #define if the welcome text for those who have permits is activated you can use "true/false
      Enabled: true
      Title: '&bWelcome &3&l%player%!'
      SubTitle: '&bThanks for enter to the server'
  Commands:
    Hub:
      SecondsWait: 3
    Warps:
      SecondsWait: 3
Messages:
  Errors:
    #defines the error of "not permissions"
    NotPermission: '%prefix% &cYou do not have permissions to run this command'
    #defines the error of "not exist"
    NotExist: '%prefix% &cThat command does not exist use /je help'
    #defines the error of "error argument of get"
    ErrorArgumentOfGet: '%prefix% &cPlease use <version/author>'
  #defines message of reload
  Reload: '%prefix% &bThe plugin was successfully reloaded'
  #defines message of hub and warp
  SetHub: '%prefix% &bThe hub is setted in %cords%'
  DelHub: '%prefix% &cThe hub &c&lis deleted'
  SetWarp: '%prefix% &bThe warp &3&l"%name%&3&l"&b&l is setted in %cords%'
  DelWarp: '%prefix% &cThe warp &6&l"%name%&6&l"&c&l is deleted'
  #defines message of hub
  Hub:
    HubTeleporting: '%prefix% &bTeleporting hub in %wait%...'
    HubTeleported: '%prefix% &bTeleported to the hub'
    NotExistingHub: '%prefix% &cNot existing hub'
  #defines message of warps
  Warps:
    WarpTeleporting: '%prefix% &bTeleporting to the warp &3&l"%name%&3&l" &b&lin %wait%...'
    WarpTeleported: '%prefix% &bTeleported to the warp &3&l"%name%&3&l"'
    WarpError: '%prefix% &cPlease use the command /setwarp <name>'
    WarpError2: '%prefix% &cPlease use the command /delwarp <name>'
    NotExistingWarp: '%prefix% &cThat warp does not exist or you did not enter a name use: /warp <name>'
    WarpListLineOne: '&3&m&l-----------------'
    WarpListLineTwo: '&3&m&l-----------------'
    WarpListUpText: '&b&l        Warps'