Config:
  #prefix that you can use with %prefix%
  Prefix: '&b&lJoinEvents &3&l>>'
  IpsProtected:
    Ips:
      - 0.0.0.0
    Names:
      - 'player'
    KickMessage: '&c&lYou can not enter because this account is protected by ip'
  Join:
    WelcomeMessage:
      #define if the welcome text is activated you can use "true/false"
      Enabled: true
      #defines the text of the welcome message
      Text:
        - '&3&m&l+---------------------------------------+'
        - '                      &bWelcome &b&l%player%'
        - ' '
        - '     &c&lYoutube: &cYour Youtube'
        - '        &3&lTwitter/x: &bYour twitter'
        - '           &b&l¡Visit our store mc.example.net!'
        - '&3&m&l+---------------------------------------+'
      EnterFirstTime: '&3%l%player% &b&lin a join for the first time!!'
    TextForRank:
      #define if the welcome text for those who have permits is activated you can use "true/false"
      Enabled: true
      Permission:
        - 'je.vip'
        - 'je.vip+'
        - 'je.mvp'
        - 'je.mvp+'
      #defines the text when someone with permission enters
      EnteredMessages:
        - '&3&l[&b&l+&3&l] &3&lV&b&lip &b&l%player%'
        - '&3&l[&b&l+&3&l] &3&lV&b&lip3&l+ &b&l%player%'
        - '&6&l[&e&l+&6&l] &6&lMvp &6&l%player%'
        - '&6&l[&e&l+&6&l] &6&lMvp+ &6&l%player%'
      #defines the text when someone with permission exit
      LeavingMessages:
        - '&4&l[&c&l-&4&l] &3&lV&b&lip &b&l%player%'
        - '&4&l[&c&l-&4&l] &3&lV&b&lip3&l+ &b&l%player%'
        - '&4&l[&c&l-&4&l] &6&lMvp &6&l%player%'
        - '&4&l[&c&l-&4&l] &6&lMvp+ &6&l%player%'
      #defines the sound when someone with permission join
      SoundsJoin:
        - LEVEL_UP;10;2
        - LEVEL_UP;10;2
        - NOTE_PLING;10;2
        - NOTE_PLING;10;2
    Titles:
      #define if the welcome text for those who have permits is activated you can use "true/false
      Enabled: true
      Title: '&bWelcome &3&l%player%!'
      SubTitle: '&bThanks for enter to the server'
    #defines what the actionbar will be like
    ActionBar:
      Enabled: true
      Text: '&b&lWelcome &3&l%player%'
    Fireworks:
      #The options to set are: ball, ball_large, star, burst, creeper
      Types:
        - creeper
      #You can put any color but remember that it has to be a decimal color code and with the #
      Colors:
        - '#4444'
        - '#00fff5'
  Commands:
    Hub:
      SecondsWait: 3
    Warps:
      SecondsWait: 3
    OnConsoleJoin:
      Enabled: false
      Commands:
        - 'gamemode survival %player%'
Messages:
  Errors:
    #defines the error of "not permissions"
    NotPermission: '%prefix% &cYou do not have permissions to run this command'
    #defines the error of "not exist"
    NotExist: '%prefix% &cThat command does not exist use /je help'
    #defines the error of "error argument of get"
    ErrorArgumentOfGet: '%prefix% &cPlease use <version/author>'
  #defines message of reload
  Reload: '%prefix% &bThe plugin was successfully reloaded'
  #defines message of hub and warp
  SetHub: '%prefix% &bThe hub is setted in %cords%'
  DelHub: '%prefix% &cThe hub &c&lis deleted'
  SetWarp: '%prefix% &bThe warp &3&l"%name%&3&l"&b is setted in %cords%'
  DelWarp: '%prefix% &cThe warp &6&l"%name%&6&l"&c is deleted'
  #defines message of hub
  Hub:
    HubTeleporting: '%prefix% &bTeleporting hub in %wait%...'
    HubTeleported: '%prefix% &bTeleported to the hub'
    NotExistingHub: '%prefix% &cNot existing hub'
  #defines message of warps
  Warps:
    WarpTeleporting: '%prefix% &bTeleporting to the warp &3"%name%&3&l" &b&lin %wait%...'
    WarpTeleported: '%prefix% &bTeleported to the warp &3"%name%&3&l"'
    WarpError: '%prefix% &cPlease use the command /setwarp <name>'
    WarpError2: '%prefix% &cPlease use the command /delwarp <name>'
    NotExistingWarp: '%prefix% &cThat warp does not exist or you did not enter a name use: /warp <name>'
    WarpListLineOne: '&3&m&l-----------------'
    WarpListLineTwo: '&3&m&l-----------------'
    WarpListUpText: '&b&l        Warps'
  Fly:
    Enable: '%prefix% &bYour fly has been activated'
    EnableForOther: '%prefix% &b&l%target% &bfly was activated'
    Disable: '%prefix% &cYour fly has been disabled'
    DisableForOther: '%prefix% &6&l%target% &cfly was disabled'
    NotPlayerFound: '%prefix% &cThis player &6&l%target% &cis not online.'
    ErrorNotArgument: '%prefix% &cPlease use /fly <player>'