main: me.thedogsito.je.Main
name: JoinEvents
version: 3.0.0
author: Thedogsito
api-version: 1.21

commands:
  je:
    description: Command that brings main sub commands
    aliases:
      - join
  sethub:
    description: This command allows you to put a hub
    aliases:
      - setlobby