main: me.thedogsito.je.Main
name: JoinEvents
version: 3.0.0-RC5
author: Thedogsito
softdepend: [PlaceHolderAPI,ItemEdit]
folia-supported: true
api-version: 1.20

commands:
  je:
    description: Command that brings main sub commands
    aliases:
      - join
  sethub:
    description: This command allows you to put a hub
    aliases:
      - setlobby
  delhub:
    description: This command allows you to go to the hub
    aliases:
      - dellobby
  hub:
    description: This command allows you to go to the hub
    aliases:
      - lobby
  setwarp:
    description: This command allows you to put a warp
    aliases:
      - sw
  delwarp:
    description: This command allows delete this warp
    aliases:
      - dw
  warplist:
    description: This command allows show the warps available
    aliases:
      - listw
  warp:
    description: This command allows you to go to the warps
    aliases:
      - w